### ISSUE TITLE
The busy signal seems to be given too early

### ISSUE THREAD

**Issue by choucl** [yuyuranium/vlsi-hw0#4]
https://github.com/yuyuranium/fpga-hw0/blob/1324f08d2fea97724c6476ecfc901e88508b1388/Controller.v#L34

The `busy` signal should be high after the `en` signal is given. Otherwise, the simulation would be failed if we shift the `en` signal a little bit later, i.e. adding a `#10` latency after the `rst` is released, in the testbench.

**Comment by yuyuranium** [comment]
@WillyChennnn Please have a look. The `busy` signal seems to be pulled up 2 cycles earlier. It should be set to 1 with the posedge of clk after `en` = 1 (red line).
![image](https://user-images.githubusercontent.com/79467307/156303465-ad320092-6d4f-4199-98a3-e38e05523e81.png)

### The spec
![image](https://user-images.githubusercontent.com/79467307/156303591-d76ed00e-4ebd-4903-863f-510ba69c4243.png)
